apiVersion: v1
kind: Namespace
metadata:
  name: k8s-program
---

apiVersion: v1
kind: Service
metadata:
  name: users-db
  namespace: k8s-program
spec:
  selector:
    app: users-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  clusterIP: None
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: users-db
  namespace: k8s-program
spec:
  serviceName: users-db
  replicas: 1
  selector:
    matchLabels:
      app: users-db
  template:
    metadata:
      labels:
        app: users-db
    spec:
      containers:
        - name: users-db
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: root
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: usersdb
          envFrom:
            - configMapRef:
                name: initdb
          volumeMounts:
            - name: users-db-data
              mountPath: /var/lib/postgresql/data
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d/initUserDB.sql
              subPath: initUserDB.sql
      volumes:
        - name: users-db-data
          persistentVolumeClaim:
            claimName: users-db-pvc
        - name: initdb
          configMap:
            name: initdb

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: users-db-pvc
  namespace: k8s-program
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "hostpath"
