apiVersion: v1
kind: Namespace
metadata:
  name: k8s-program

---

apiVersion: v1
kind: Service
metadata:
  name: user-app
  namespace: k8s-program
spec:
  selector:
    app: user-app
  ports:
    - protocol: 'TCP'
      port: 8088
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: k8s-program
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-app
  template:
    metadata:
      labels:
        app: user-app
    spec:
      containers:
        - name: userapp-container
          image: epamalesiaskarakhod/userapp-image:1.0.0
          imagePullPolicy: Always
          env:
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: user-env-config
                  key: userName
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: user-env-config
                  key: password
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: user-env-config
                  key: dbUrl

#  volumeClaimTemplates:
#    - metadata:
#        name: users-storage
#      spec:
#        accessModes: [ "ReadWriteOnce" ]
#        storageClassName: hostpath
#        resources:
#          requests:
#            storage: 1Gi
