version: '3'

services:
  users-db:
    image: users-db-image
    container_name: users-db-container
    environment:
      - ENV POSTGRES_USER=root
      - ENV POSTGRES_PASSWORD=password
      - ENV POSTGRES_DB=usersdb
    ports:
      - "5432:5432"
#    volumes:
#      - pgdata:/var/lib/postgresql/data

  posts-db:
    image: posts-db-image
    container_name: posts-db-container
    environment:
      - ENV POSTGRES_USER=root
      - ENV POSTGRES_PASSWORD=password
      - ENV POSTGRES_DB=postsdb
    ports:
      - "5433:5432"
#    volumes:
#      - pgdata:/var/lib/postgreqsl/data

  user-service:
    image: epamalesiaskarakhod/userapp-image:1.0.0
    container_name: userapp-container
    environment:
      - ENV DB_USERNAME=root
      - ENV DB_PASSWORD=password
      - ENV DB_URL=jdbc:postgresql://users-db:5432/usersdb
    ports:
      - "8088:8088"
    depends_on:
      - users-db

  post-service:
    image: epamalesiaskarakhod/postapp-image:1.0.0
    container_name: postapp-container
    environment:
      - ENV DB_USERNAME=root
      - ENV DB_PASSWORD=password
      - ENV DB_URL=jdbc:postgresql://posts-db:5432/postsdb
    ports:
      - "8089:8089"
    depends_on:
      - posts-db
