apiVersion: v1
kind: Namespace
metadata:
  name: k8s-program

---

apiVersion: v1
kind: Service
metadata:
  name: post-app
  namespace: k8s-program
spec:
  selector:
    app: post-app
  ports:
    - protocol: 'TCP'
      port: 8089
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service
  namespace: k8s-program
spec:
  replicas: 2
  selector:
    matchLabels:
      app: post-app
  template:
    metadata:
      labels:
        app: post-app
    spec:
      containers:
        - name: postapp-container
          image: epamalesiaskarakhod/postapp-image:1.0.0
          imagePullPolicy: Always
          env:
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: post-env-config
                  key: userName
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: post-env-config
                  key: password
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: post-env-config
                  key: host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: post-env-config
                  key: port
            - name: USER_HOST
              value: 'user-app.k8s-program'