apiVersion: v1
kind: Namespace
metadata:
  name: k8s-program

---

apiVersion: v1
kind: Service
metadata:
  name: posts-db
  namespace: k8s-program
spec:
  selector:
    app: posts-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5433
  clusterIP: None
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: posts-db
  namespace: k8s-program
spec:
  serviceName: posts-db
  replicas: 1
  selector:
    matchLabels:
      app: posts-db
  template:
    metadata:
      labels:
        app: posts-db
    spec:
      containers:
        - name: posts-db
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: root
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: postsdb
          envFrom:
            - configMapRef:
                name: init-script
          volumeMounts:
            - name: posts-db-data
              mountPath: /var/lib/postgresql/data
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d/initPostDB.sql
              subPath: initPostDB.sql
      volumes:
        - name: posts-db-data
          persistentVolumeClaim:
            claimName: posts-db-pvc
        - name: initdb
          configMap:
            name: init-script

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: posts-db-pvc
  namespace: k8s-program
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "hostpath"
